---
- Media:
    - Audiobookshelf:
        href: https://audiobooks.homelab.blacksd.tech
        description: Audiobook server
        icon: audiobookshelf.svg
        widget:
          type: audiobookshelf
          url: http://audiobookshelf.audiobookshelf.svc.cluster.local
          key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}}"
    - Grimmory:
        href: https://library.homelab.blacksd.tech
        description: E-book library
        icon: mdi-bookshelf

- Tools:
    - Linkwarden:
        href: https://links.homelab.blacksd.tech
        description: Bookmark manager
        icon: linkwarden.svg
    - Paperless-ngx:
        href: https://paperless.homelab.blacksd.tech
        description: Document archive
        icon: paperless-ngx.svg
        widget:
          type: paperlessngx
          url: http://paperless-ngx.paperless-ngx.svc.cluster.local
          key: "{{HOMEPAGE_VAR_PAPERLESS_KEY}}"
    - Vaultwarden:
        href: https://vault.homelab.blacksd.tech
        description: Password manager
        icon: vaultwarden.svg
    - Minecraft Bedrock:
        href: minecraft-bedrock.minecraft-bedrock.svc.cluster.local:19132
        description: Bedrock server
        icon: minecraft.svg
