apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc-data.yaml
  - pvc-meilisearch.yaml
  - cluster.cnpg.yaml
  - secrets.externalsecret.yaml
  - secrets.sops.yaml
  - httproute.yaml
  - backendtrafficpolicy.yaml
patches:
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: linkwarden
