---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: linkwarden-nextauth-secret-generator
  namespace: linkwarden
spec:
  length: 48
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-nextauth-secret
  namespace: linkwarden
spec:
  refreshInterval: "0"
  target:
    name: linkwarden-nextauth-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: linkwarden-nextauth-secret-generator
