---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-rawfile
  resources:
    requests:
      storage: 10Gi
