apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-oidc
  namespace: linkwarden
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:2MNUeOioHdhJ+ds/v6TUfDpfup74KuZRmDcZ5UiHVI5B+SUGO2tpQw==,iv:brUj14SzUHTQtMZV8EqR3E2VIZ0cYRVMvFT7I3xg6J0=,tag:A/DdNo2pos9wfPK4grKU3g==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SZ+JodwRy+BVbKB/rA91klN9vIV4I5XFgyyR0ki6LVeuumCW7n34emZbtfAqzxBwf6yoUEcOs8NlNy3EssFPlQ==,iv:t251W04PjFIUgSP8+xxqq4g+mmAjshlgNoXBPvjz5X0=,tag:g8e0IHkh3sIDbJisdGrdPA==,type:str]
  OIDC_WELLKNOWN_URL: ENC[AES256_GCM,data:csqg66CyoIyq8XHoI+5k0k6a0twJ8Ph8TYYwZpFuBEi0AVvATXjRFyUJniXSElpFWw4q8mL7TsidX7BALMqqWaN4F5E/NKllELr0wPDndD8c1MjrrVko6AA=,iv:UvrxVuNMNLks9yJLD+MFPA3mCp8miglq+r8BiQlFyjw=,tag:sfl6P1rcXoZVtWwllmdLQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVJUY01xUTg4Y01GNTZv
        RWd2OFJPUUZYQi9RMENHUW5qRUE5STNWelVvCjdvRjY3dFQ3dmxCQi9XeEk5NzZD
        OFVOQmhrYWg2bW9iZThXRDBDWVNaS3MKLS0tIDZYT0Vud1hDZExGeFYvR0ZaMHg4
        M2U2enFPQ1RTQndEc09XWERZQjJKdm8Khs68NGOEdhQxAJA6DoathYMUptnD9VOW
        wn7n9XLBGr3Onj3P/Jn4jUk08x9WMTGgLWybkguVmUm4xfATByfm/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWUNUZ0VZeFV3M0NXNVlG
        TzVWeUdwd0hJQUpTaElod283SzMyTHZERXhJCjNhcEM1N2M4RFVmcm9aSnJLL2sr
        RWdLUlJDSUlRSW8zbFZmWVl2anpEU2cKLS0tIG9PdXM5ZVYrNVRxbWo4M3F0SVNo
        SENoQ1g4bjgyajc4Z3NoMDZZRmMxRWMK0KGI/5OhiQsIURCRJytVIWbCCqCB+vyR
        MzZxgexxn4S5XGQflt6mGdU9RFVAdtPR8EfDYjnLpd0kD+zW/Q2V6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T08:28:46Z"
  mac: ENC[AES256_GCM,data:WEH9KSPSDtrPeN6pPAPyBfFVlrT92B3VX45FfgojQZcnz5jzGWVe4DX2Iw1P265OZxErBYHzT5Ws4imNydW4JzSLLVBA7IF8ElzJBGinw8zD6LceiLkrgQNThCDsDHGbfPG3QjWvaSiM6BqdSp08BxVf9FqGYaG9/SbhbG9C+fk=,iv:SRYhOsr7qFdtyJTSaUG8sRzLMgdkLtTDWp4siXGasoQ=,tag:3YYc5IJVC+4Ms7LaLwa2rA==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-08-15T08:28:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaARAAzbsq0GTWFakf9Jv0vVO8czFo1UFS2a+JHneMon/PCBqe
        hNt7wAxO8BMC78Ak8kWhpvmDjl/p9xjriQ92pCVDmVv9qD4WeSnbrskluN1O+ula
        KMj7ECbBRcwsPboEhEEvF6SWoJd52Rg3SM+zsdPHZ5Blc0uY1zxiwEH/fPMd1R6T
        pkDSm6ZLC3zaokIrkZXEVz2Y/JTSqU0a7RJilN3OonNr7TbfwcZ+D/oPqqrFFJy6
        7lq+qR8aS95jqjgCa2PuGHR1U43MCZYSae36huNknQW1LlPSSKua0q01ahcXbcDF
        mvePeqgYqiHVHiJwu5CXzuZ7bK3ljDNOH8TGSVEVI9/uaEIjqFf6tDmrBofh2gdp
        3nzQMbWJoIAsipt2OD3gfloht7j2kEPsbmyZFvdezAolBtNVMi8ptt/IEaN47lT4
        aeAe59Mdr+TEqUmm2ohWNXfrQ4I/Tt6E/b+Q1DmDSHQ2VM5nFTNweO7wR/WilJBu
        H1U8sjWQ21naawZ6pTbp17hMeEND4cwioQAzY1wCvggnzQ227qopGb7nbyxkIRSE
        z1j0giMl8cVhcKYKIdsd2geYoDyON6bDsmmjvbUxPERD/pcnuK+TwU5aoRYzaPi3
        yfo9/skWnitPA5kDc8yB92mbIMzVprXwlz74JTKv7+4FBZ4sdHCIh5bZSG9+z53S
        XgHWh+tQn1FnbnGWfOjGP6y/HqDG21GaRAYd89KJzFJxoU5orzEWWe5PDtt5D+Ss
        Z1kki1xjdoqbUdCS5OBnGtlRDEjo7jnjyj3d5xmnWjMch/Tfw8/XOqkguvrji0Y=
        =p1cE
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
