---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-data
  namespace: readeck
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-rawfile
  resources:
    requests:
      storage: 5Gi
