---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: headlamp.bat-corn.ts.net
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: headlamp-tls
          hosts:
            - headlamp.bat-corn.ts.net
