---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-secret-key-generator
  namespace: netbox
spec:
  length: 50
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-secret-key
  namespace: netbox
spec:
  refreshInterval: "0"
  target:
    name: netbox-secret-key
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: netbox-secret-key-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-redis-cache-password-generator
  namespace: netbox
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-redis-cache-password
  namespace: netbox
spec:
  refreshInterval: "0"
  target:
    name: netbox-redis-cache-password
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: netbox-redis-cache-password-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-redis-queue-password-generator
  namespace: netbox
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-redis-queue-password
  namespace: netbox
spec:
  refreshInterval: "0"
  target:
    name: netbox-redis-queue-password
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: netbox-redis-queue-password-generator
