apiVersion: v1
kind: Secret
metadata:
  name: netbox-oidc
  namespace: netbox
type: Opaque
stringData:
  #ENC[AES256_GCM,data:oPRPM83X2vmSwI7ReO3qrZ55MW6zORHfCTuIMzsn+gOlK/vEdSDDp0E+cT/YfdnF29WJjQ==,iv:zukoNC68zcFv7PFuEsAo8Tvk9kHH8HF6DRPRsgFvmfA=,tag:x2VAetWD2LqgtKYgxmvN9w==,type:comment]
  #ENC[AES256_GCM,data:GjXV8ZUt/McKiQMrd6Mq1Imv8TL8MP1w2XSsV0BdYuYhx4oyr+iak851aSfINSbbrzqD3XqCRRfGKXNtLU1VYG8l,iv:ApOmCkQxEkdeCSLow6H4WWVV36EXnfkRzh2+m3MM0qw=,tag:COMYsEGVe+ZLBhjTZxta8A==,type:comment]
  #ENC[AES256_GCM,data:5l35qIzvLk767hjsblUuoL2A/psGK4BKcA/0sgwtItjloYar7UJLu3QgS3SoMJeCnIwEXiBJfdHXPm6UuBYCX7k=,iv:B6XwOVDOc2+95Y8WpAnbHYb2LRWjw6SnpOgsvOBu2TU=,tag:bJEzn+cR5b7UqA+SqC4uPQ==,type:comment]
  #ENC[AES256_GCM,data:98JJZt6+FedxwJckQXggJIqd2iEaKDzguH4PvugAARAcEK+Bcpdb+3fniO/ZfcKFs8g6BBGZlk+Z6JoiHA==,iv:Zo8vHw1BGayITHj0rTuEauqOjU2H9EhkhHqmZOjS2rc=,tag:KxDzpv2YT2G30hUn5kcY2g==,type:comment]
  #ENC[AES256_GCM,data:0Ucx9KoLop639YrLQ+TEaLMI0QI888ETEUaygwZJIRz5/0lP14kDMi53YcqHTIeBHYgjQWrMsD3CJPt9JrwYflQ=,iv:HCelX1VU8efEyR5sni3//xovEoL3iM+RNuXEgoh6bHI=,tag:7m4xI3wsuMkc3NuUGUcAXA==,type:comment]
  #ENC[AES256_GCM,data:/iI4rqpWuaJ9ocDBUeZ/T1qgvHJMJb3wgV5u4jF1mqQq+yniNk3zZCbQGi27w3eeyw6oLB5+ml76dO8Xx7NnESQK5liY,iv:FSyqnSjOeMsXRnSPpkEZqWS3AWS/cW4oq5IBeJXq4+4=,tag:SNszKowiv64ZoedOtxInRQ==,type:comment]
  #ENC[AES256_GCM,data:N1sN99E/8A==,iv:dI6txQjg95X4xL5YWWVZD6sXZoQSw8/l4H6BktvctV8=,tag:cSo8R3ViIEOl7UxQDUwYZA==,type:comment]
  oidc.yaml: ENC[AES256_GCM,data:i6EKEJGYruZTXi8rjhO52DvfckX8yW0xVD1sLNXZMmMjBHZMuaoduqO1GCIPB/eDFK4F7eO/tjeFu9Yb/I3L7T/eaJVOf5qkAs7A1XcTciMK42csvndMiLCRBexvpSS9Lrs8DePFW99PecbPR24uxXie3ZQbEoOfonxn0gCZcNsjfsbQZzDy0OmZEC+p5fDYXfSqsSk7LdTG,iv:LYB57o22Ucz1xStwcnLCgReTPZjNeu9+LjDrfE6ENVg=,tag:p2I6M65k/eGawdro0LhnAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZDl5OFA2KzVZRzRWTTY5
        clpYVUk3SkY1dVd0MmRXZ0N5aUE4OS95M2lnCnBNSkJoVUhPcFNxdUh1NXFRbWUw
        U1o2d2tvbnYvckkyREo2N2R0dXIrM28KLS0tIDRYQ0svSi9FQk1TOUhER2ZPSGZZ
        MjY4MXdyenlPb1JxVXdzRktpbGtGY28KXyZulHbWFL8RqPZNsncmyO76YazhqPCV
        hE6C0Pb8vIv9lCIWDe0AwfH9hlqvuRkodgbGa04FGzjteyxuhDbEgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdEtwMFlxYzVkVy8vSXdq
        RWE1Q2FlT2o1ZktHYjJQSmxzajRZTTV0WVVZClZHbGtWOUVzN2FPVTJqd1UzRkhh
        KzcyMW9MaGdhYlJLc3paT0xIbHo5YWsKLS0tIGl4UGNaUGI3YjNrUG00bmllWDNx
        ZmduWHd6RG5RbFBBTDdYY29LdFljTjgKOhOG/2MlL42tq6/fa61Jd4umo6TUp738
        vWVexMNbWywXvwGIb7AxgnKNXM/OkiPrgX0NQs7mSrUqkXDyyehBGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T11:15:02Z"
  mac: ENC[AES256_GCM,data:O2G81vQITNPh0Vp8TVWflFIVhSAmFI0dR3ph0X0T1NI6O+/su4+Q0gbMX5zwZq5moKwDLjThEuswdBQmXJ2IJP0A3VWAXhlYGSTR7MWAMSQqSJUA7/hfLgiIFG/z793SIZyQ5PmTfBEfTPkstQqYQgO/TE08UESJb8/t8ic7x5w=,iv:ft5/gRr94a/Zf9fvLS3afTdUKS01oeSh65aNORTQ9n4=,tag:VW/c5OkYFqN1kELK9EzyJA==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-08-16T11:15:02Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/9HZ2eAjvQURuruJQSYxbQHLqTyFiXu5J4fAF69B0HQavO
        84lpgINZGx8zicJ5spYmoLZG4uDbjWwX3YZf/2JuJdm3eR7xfPLaEtlj3j1rbxuX
        rszTwSoed6MzlzghQqC1PkPOSgGl1lxp7SFq52rc9VZ8ACBtB4HYQ+Y+dvIUuC0V
        2hMSXqLPbfC8ieLNhthW9uzYlT0zk++70ve412FejR4GgQiP/9NtBEjxOfk5PpqL
        7+HQfpg1qq1gC3JZC/aV6FVSt6DTc081PrxKk6/V994miKspV4ywvinaIRORnKPq
        S3yJ50jlFNxlqZA1Pk8LFetD9+JYnib/UPFbMdYPkZfZkShxzhdRmIkshLuHvaZs
        w2rqOoY/cRn334wFxiWKe6lwhLkTmhGV02FNxHzm3kKiCvIBvrUbbWxk4enf2uwy
        sjAJcfAkHY/6icByKKKYCXh2HsQYBj5O/Ms5BJ+LcYqHAq4Dz6SXvt6zL67rfPrx
        Ea5wJ4WA1PvMqLUx35pObwaoFirn0f0ZmfM2J81dNwjC6FVUWfoXBfspAFAsrs71
        70ioPz0ZG54EHrBH0zgbISlziLfhy0wHNwq9uDepBdYH1m6t4j4Tl8NMRiAhEr3u
        hfKkcX0IpKJ40VqexZttAdKrWfzhUgJ881Am/0VvKmN1IXwmPURabmgg7H2e2vfS
        XgGeLeNZAy2T3CRLUmeeaH4t9Du5qZVfsekdClwBGvQ6tIqPpsw29AFzZ/9fCro6
        z+ti/8c3PK9ABMyUVbOj1VWQCfYt4TDzObp2z9wY6oDIWGvVMLdKE/J1nj5fr+E=
        =m4oe
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
