apiVersion: v1
kind: Secret
metadata:
  name: netbox-oidc
  namespace: netbox
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:sPiDF995PQvF88y/YOGQ36F1ETtc+e6Xpf+qE4pmt+WnVkPTIOIAmw==,iv:t6ucXLiSHQhCPBvkLjVe8xi7jWYmMl98Q7pvehZeAyw=,tag:V5yAdSYJnxduUvLBGhZSbA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+9qqEzHULxDMf+0DDdquy/sw0fybl2VnrqXVXwmeIObIx13WD1hcK1tm4he97X2kRxi3sYJWWeV0Ci32G/7yHg==,iv:cHQn0p4dfcKNMevDoi78dH8BoFZqJLT7T7EKN/pux80=,tag:ELhrhBIb0C9yjSJRVZ3eew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vm9tbEFnOW1aTkRXZmdF
        RUMxK3BuS2tOdE1sazFGWDB6bG96UjZhZjNvCjd3Nnl3WS8xQjBrT1hrWmhzQlZZ
        RndJYzF0c3hMdy9xRk1RWHpVc2c5Y2MKLS0tIHdwMkVOTGMzRk0vcTRJdVprVXJl
        bzI5NTJ0U0JYeHh1bU5HK1NEdTlkcGMKCK449TiwoyNJkD3U1iPcHysi6+6Vv9ly
        4D5Yb8+A8wzs/hrzEW3cuK5K9D5H0TYyfHVHW6NvQcTIJsqFUnNypw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS2tOMHJnM1VURnBSTzNQ
        bFFXY0FJa1J3MDJFU3Eyblp3YlQvUGwyRVFVCjVQd01NOGxuVG8ydEpXcC9YemR4
        NnBHVEJNYjl3TGdDSCtjT1dJNmdaZ0UKLS0tIFRpajYrTG5sc2lRR0daU3JsVHdr
        V0FHaVBRZm5Ka2RHKy83Z251cTBKVlkKgcRWQpZazrfHqP4/oHSAcwPb6PEIgNga
        r5j8KKU8C0l8gilHZalCSu+Hx7/ZVS9NJJi3/wfMM5hn/s2hUaalKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T09:10:19Z"
  mac: ENC[AES256_GCM,data:uPanw7h3WXHkxhunxiHlQMBdnn4dhntRpvwGI9lxK7UQ5BmhyS1W3718PKiuc8pxL2Ee1e/lGw6/p7kcNXXti18Hz04h3J5J3t26a8uXTL8p0V+2sslTTBgIfESelI6B5aSVkrA3smoW6wRxZ7dNpSBGYiCcbBLKAhuebDuvt5M=,iv:U/pcrBABNqrjsIHNRl2Mkq0jXkfJesze/XO1uaYkKxs=,tag:nxyAnPt7RuFr7T8fqQcwOw==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-08-16T09:10:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ//ZU1YflpHe3My4ibCCi3rlC4BwGthTXNS06IoHI+IrM7p
        0VrUKGDkaFxRYvrxq5VYhwwxASS3I845AT+SxgCIm+dimxsxMsQO11jOdhfNy9ba
        CA7J1kaYc55HM8G0rTWZ6OzzpWwxhIU6Hi28RHQPXRu0gT5cdCKrXOMnyyd/dcHV
        1Yh5yu/p//PT+LUHbrs6os82cEstEZh73Cqocw33JxdwxtRKUvYJLFqACpBooVza
        9bKW+9eND4Lh2bLE0XR39doN8ahIkqAcaSIPnXQdLHr8Fmhgb30cdY/xU5BLfarv
        sxoTUJsZO2wk1aOJ2HlqcUPRU5Xas+RUHWqO0BK+vOtHgQoHT3DzSfZzvOQ4aJ6k
        tOvqYazDYpBwRyUvr+qgT0EKv/I1P6UP45WUnEgwhs3OX7AgyAKkxyqeckO5XeSy
        O+jI2KyYz0LFmoDIWaxipWSLP6Pq7aPHzPQ8OBHFqpSBsLlhnUW8XY3q6h5LxUme
        qR0aVavnicXCHPnzH7gWY9RD2Aq+Tr2YxhBAAL01b+jNi3nR71mawcWO0oUJJmrQ
        OVq5vdLNc94FTwuAOQ5zhTkAs6q/+FGIQds16FBMT95oO0zVODv6A8P2MkMx5ez0
        qt7yOfyOoJCeUpA34rKov/0laVKHzEjmED7Inh07XdpjHwtPe7fzXqFLEDg6cWzS
        XAGRs/cYiLcE28E8+HN90XjvZPY/238QveJbhdpWrfoD63bcfsKTIrQ2NC+Vm7JW
        dFDREku9gqBJoJuZxFkGR63R8zdl0jsVFsL0X8CXJwtYsJPnuI1LFG8CshWe
        =K4XM
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
