# Minecraft Bedrock Dedicated Server
image:
  repository: docker.io/itzg/minecraft-bedrock-server
  tag: latest
  pullPolicy: Always

# Server properties
minecraftServer:
  eula: "TRUE"
  version: "1.26.3.1"
  serverName: Terra di SempreInMezzo
  levelName: Polli con e senza controller.
  gameMode: creative
  difficulty: normal
  maxPlayers: 10
  onlineMode: false
  # Bedrock default port
  serverPort: 19132
  serviceType: LoadBalancer
  enableLanVisibility: true
  cheats: true

persistence:
  storageClass: openebs-rawfile
  dataDir:
    enabled: true
    Size: 5Gi

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi
