apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY: ENC[AES256_GCM,data:iCYXuariUfOuC1dP5dTRT6O045BW68h6HiM3VkSKTJOKxRM17LEbf1VaDvG4N88BwQS0GzRHVYgEvpZOFzZcVvG+/BBRM5+0qJzWlfbVW/SZRCMkrdpqhRwnwE2KUi2F9jVUGdd4MCVsk+Aea4xbG8pwHwsxuLWGGL8wFnuq/C2n4gficsfwAc+kefBdVFwRizPxt363FK9ZM/AmMwEwkiv/qyeYxPrhz0IpxzSojwY8eLttHRZNkPDUXP1M06Fq52y2AS+1IA==,iv:T6Ccpnm+9mP1xXYfwghG4Eh4IWZk0hbOBtdTAZZhCjQ=,tag:56VlISE/Fr9oBbIZb0OlRQ==,type:str]
  HOMEPAGE_VAR_PAPERLESS_KEY: ENC[AES256_GCM,data:dC1ut1T2rC3RgH6szZqfo5EiTEmKPeIM0SdmQBOh9tChIhjLA7ThqQ==,iv:+uqClEHlOxqQDRy22+yY+N/Bc8LYY6rhihfI71AET6A=,tag:+usbb0NZKrvA4wn4DjPoHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aEZPc1RGRDAwMm1CUXV5
        UldEL2ZvQ1d6cmNGWW5GR2F6VmVqdnJpMkh3CklYdmZpMWpaSHpvQ2UxbnBOenRJ
        YWE0RVBkbWV6Q3pNZzdYNDFQVVQzY0UKLS0tIFBGeUZlWUZ1ZUdkaExDL1ZSSVlz
        dkx1RU5SbzZDa1pTQVRBQVplUWtyMDQKOskoR2pOj1IU7KH24CFOZx5nn20pcHe/
        A2TF7snPwslRmbSMGEPDMfvjitNZ3aLIhjMTKOiMcFj39x+4Zg3DzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RnJWWjQ3aUxRRXZoUUNF
        TEx1ZHVZMFFYZWFQTjhsZ2lYOS8yNnV2dm5VCk1pWkE3RGRBeTJ5WmY0L2M5RStE
        U2N5ODMrVUxxRnpxeGx2WjJvWmxuNEUKLS0tIHZwRW41Mm9KTHpwUjBRZ0l1UWtK
        QkZXMytVQS9mbDI4a0pDNG1aZVhBN2MKy4breZ4SCLCSJ9VN5471TA6Z5BM/ddfj
        w/ZZXxmiyQ0VGwmO0ovkMWaNYWEamlcIfNcNYbFUBkUc5Yryfjvx+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T06:32:14Z"
  mac: ENC[AES256_GCM,data:spZoet7on7TQfeX7/sINkwsP6TH8YDpG/ABleSRC2YFN+YqrWMDRzC+XVcWGAa9bMx+XjOJaNlSc27ShzgC3IO4vCbDEoLUiqBXTxHpY8vmF4zBlRmet9Wle1a/HFe80iiXSwllN7G+oJIpO1VqZGVeE1Z+CqNzjGV7DW2+UCao=,iv:2K/seHANNXBp3xkuOyw+R/gMQC7jFMJjYY51wJ1V2uc=,tag:6QLUPR5lC1sNgCis3rRruA==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-06-05T06:32:14Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ//Uw4AZhcHHJ3bH89e+hKIeSBwLHkdfmRy+HIxTFKRbX7Y
        qebg87mLPgjGiyXoA/usFhbtrgFceD+whPU6t2sh5cf/36uirPHGrkEyUbzQR+Rt
        /8jDDtulNuZPNqFLNTxeTAhlb+rvy24ENtij7SSqsUW/BeO/PRmf4JGN/ZNOABnf
        FZm3AYbGNU6fledMFO9P4EmIM+VqZ07R9yUX0B5gwtKp9bRpGm9Jk+m98TqBfVck
        QJGXkFD4O3g16AWg0kmNkBHo+ivT6b4MfcOytGchE7QbAmGGVZtAgJtas7VyQrIM
        PBiilbPQs3VOFyCRsFFT46Yk3fY00Wlbw8SxmPLaizQaI2g7vCxaYpICQ6Hies01
        9h4p6If8WpR4OvUmE7d0sWcgogt78qVGtpkaXMxHUuzuY5XC9R8OgRTxo0RgyCcn
        Zd8WB9QEy+4IgAb2/Xx9AOA8hmLShBhF4SvxJFyojaEFK4Aned0CW7/m0iyvpqwT
        ZzTuiGlYRS3A+RHM88+cYchqLMR8sdSPw/SjyqTqM+ROYPDHzdXCYYd4WzBZPjNj
        uM2niMG+iswANRQ9V4gBY4S+qHdBgTqYqT+b52BG9ZYn6braOr45PpoHLRfaLJP+
        Z5/ao3bSCJiVQkfve64SkSCZVpEvQclAwX+EA8zZI3VSNi598yAEit7sF9A+TnXS
        XAF4EyKVwY7WQNdJfqgUkPFAHhnVV63QntUV77/LUx5qqnYvEfhJw8KUQt5io0A9
        R3XB1LKyaUs2pgtmUHsRQ/7vUH4rwdUcqC2df9P+sJuyIqWdu57BODSXcQI+
        =0TA1
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
