apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY: ENC[AES256_GCM,data:LEkqvZY7vHdTLixU3U/bx+VulgGB7jHz1nWKqTtdW5IDSsQXILiBNri1kLw7X4Or/n0wAJ7dyX7w4U0TGoPAE0OHTjDr15FUM+elchur7bs6PIjtG4dW/tNU+gD05xbQb7H4mmBtYQKig1N4vn+M9XIjxeQH8r1iA3XnpEFHGW9zchexuVP9C1wR2NfnsxUlchQisoG397tyROKy71XgUpIcPCnG5G8SCBf4NYQFmsRbYO8ovYwHLtCRW6stwT5cLVNizkkikQ==,iv:HUQJAaxD5rRFXfcyM5ZagIf1jRtkbNYReC6oYRVwQ3s=,tag:Fr+glrYgwdmqZHuWglguSQ==,type:str]
  HOMEPAGE_VAR_CALIBRE_WEB_USER: ENC[AES256_GCM,data:g8RK1KV+P9g=,iv:uDtdznB7aQQAJVtnBAz5WuoH/He7YBm5MIK8VsMoI1U=,tag:h/g7VuUEMgrLOAyYIOCQgA==,type:str]
  HOMEPAGE_VAR_CALIBRE_WEB_PASSWORD: ENC[AES256_GCM,data:vmV/d2Ls9oaI,iv:PsOwYfy3in5iSzh373PH22tYRSHrRKhVs9xUUy98cUY=,tag:+0hbJOgk/TBYAMyblBwWbg==,type:str]
  HOMEPAGE_VAR_PAPERLESS_KEY: ENC[AES256_GCM,data:d38G91DbNxQ+Z2ukyewdnyFaL6GivKwFFXtwP8kf5YOzoZC/Q5xHtA==,iv:SdTzpzmY9+Bk9wCPc/l9EzFJmYEbI65DPIl8gOquBTU=,tag:h9fqcStCiI/lCpQh0fhm/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MVEybVA1Q2hybWwwcTNp
        K3hzOU1CaUVUcm13WTIyY00wVzJLQ3VvdkRvCnFBNGMzSys4U3p3bEhvUEthUFly
        OG9wRmlyd1NocmYrdTVocm5rYUthQ2cKLS0tIHN6bUhLNmRadzN1RWdzRGhpemtQ
        RHFBbjV6UHhXNHI2ZmFOb0RpdUJWYzQKI4s0DzBAz/RbAKtCeK4BwPLONaLXrCMj
        qVjmN5GH9xGzDv0Bt1V9qbcytDdHHVjbKEE42POWakMndWXh6osJkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraWpxbE5OQm5hNEJ1RnZy
        UFpZYzltQS9HZGdnWjNLM2JWQTV1SzJ4c1FVClVIU3VUR0pUUnAvWEg0QUUyNGtC
        MGVrMnhzd3pwNkg2bHBra1pQUzNKRVEKLS0tIGNpRHpKQkI1by9RZUNoTTJEc2Ja
        VFdQdkFPNlE1cm5LZWFiOW5sWC9TVDQKByxa4euTVVfcQ/8MVzMnbb2yVIf5AeCj
        N7PeUL97SuGBX8ntk57t6bEDFhHWrS975ZB/ApveA3QAgnooU7Ckew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T07:04:42Z"
  mac: ENC[AES256_GCM,data:HZet5k5L2qvXXh7fldGHTkm6vdRUTZVAIkr0Lpyae9lMN/EkKCGg8ByTSa7paabj588aesoQ6mSYRylLCG3qhQrt/2tSoHyJYzPpmwuv05BPBW2Ijpex89lCuD1xsOBKvEVTzY1cjdFXyKbWtI4WtDEDHlBURTmclN8yi4SypKM=,iv:suSlKr2KwCD1DuMwknscB+rgCNb3R0AMwdUiST5Qc/k=,tag:VtwtlHXabi210rNyxFBFCg==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-06-04T06:49:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/+ICortRwNGnjfqqM5RJ/Su6Dwx6byC/QB90zev+QcA+8c
        XgmFPhqUNCXCxPEQA8hGGz0scQeCFY9cVHACZBfQZkZgxlGteIum1oD7ZG3SjR7A
        dHz7MOi6PFzEntvauIC7pTyL1v2NJbtLYmOY/fJeH1TWEzV7zcxi6nXtpIF5e1NY
        kG4ZBX+OTKTzJEFcUbcTz8TL5Bm20meCzyIJ+xfHTtv9uIZC9xc3ZGtckSloVN1G
        OhdzV/+gx3rA9WoxjavPjKW4kKwgDWPsxH2HhL0uZft0xtqKctBo29P+Z6kQY12Y
        9HNcHkXi+lpc0tS7SSO1BJOQZO+qNVmx0HXwvq21PqKSPrOkGSuwKrc1VdSkQJQI
        1rrZbI0urGajTmxNaLUyQQ6D2vNJFlYhfiT7oZxnqqAKyAViSDStXgmUB2T6aOvO
        DUhfPRhDDNBQ79o6N8s4hdUcVdFX/BIniHnY1gWbRnaI5nqwve0so9DX9jeUXlJ3
        ce7hZ+0djzgFtSLtakujbsYeRgoMCv74Fh7DLtKFvlqz4dNIbPmXBd6qjwVnAx7o
        lx/2mjBct9s16iTfnuP4Bn52qBNu7zNyA0pow/bg1ohcqQCCK3DHXLCsVTfZIjdi
        ncy/XL4peNOU/rrt14hWsVLX42NVRqBRqx6IlCfoLlZXr61MPSh4AItThPFLLZ7S
        XgFxfq6Qc2sAy4Q05FlWy1+uI/afWJO7DZ16pMBPfjU2Aw8zsMOe1ZCgm+56Mv0P
        J8lg7DIoLZ0Ftoq/O9Dh+ZZ3UHrp30EkQyyG8YXnVxuZOyqSQfapTOmQV3CtyNc=
        =F56C
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
