---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: audiobookshelf-media
