#ENC[AES256_GCM,data:iu8XlfS65KlTFIG9ciaNfFMxX4SVQNu7A4E8Yj93nZk=,iv:xLt0IEYmuUqvX1vBeKtiKGrLRpS1iZUG1zcKOfx7eV0=,tag:A4moxO5HYWw4Aw+Fpzcdtg==,type:comment]
#ENC[AES256_GCM,data:2ahMPHEmd1AKzENnk/RxrFFVHLZN0A==,iv:GNCQN+g4ikCbgsUIwqxqsdHjFCvM20/nWQdrIA/e5cQ=,tag:ytTnnd4u3LmxkU7UMG/lLw==,type:comment]
token: ENC[AES256_GCM,data:bKbqPSyBEyAqVNGRpQ6EhrShK3xMmPIbu0sxabiuAxJ3DlS6dclZJGuhO8MmMwy0eNqwX9TYLBvD+3fs,iv:hiA/EOQWPWag0dVK/q+Dds+E5uUeyiNLd1+rfUeG2CE=,tag:vn5JEQ2Ms+/io4LholQsgg==,type:str]
sops:
    age:
        - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGVvYm02TTJXKzA2TG91
            OEU2L1ZuZ2dmNGljOEUrVlNVVDJwak5ER2o4CmtoYXdJdDUzcWZ2dFh1T1hvWHhU
            STJab1Y0d0dhTXBUMjNHTldXT2VwaGsKLS0tIFVPamlzWnBZQjE0OC9aZWZRS1F2
            NzIyZTdybjRlYllMMm5xMGNSV0hEOHcK8RUBiOsvvTbnX/iPA7rqZhIrI0AwnPM5
            vVlqoArY8XZABeGuT8YS5V+Vyp9I/Vqq2tgRxBHqOxAg6/3713KUoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T09:33:16Z"
    mac: ENC[AES256_GCM,data:jcfuq+NIx+PlZNe1BcVO0uOg6liayhNF9zgsoSZ8q4Tv3bObXTD1mKc4eXHdBoy1bhw3T2+OATa+9v95SBhpg54ktTO3qWReNcLt9uFq81biWL9VSlRFUSqZqqd1YQNvQgEnYR8Tsm+iyEbKaDdVVCnIVLelHUIpFC+tcEQfCQU=,iv:MS8cqdnAGFsMY3AufZYM3Q8g7fIDJKjj7DRcO4gKSw8=,tag:ReSaq89oDuPPCjF+yRrk/w==,type:str]
    pgp:
        - created_at: "2026-06-14T16:59:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7McDQbiwetaAQ//fa5kGdmtSeNk2FebZdGbSrKjQVcD9+Ext2TCTHGU7NTy
            aKqXsaE/VdoBG89ckArOSHacUeh1WZe+z/JnCqbLzAzxj1IFpmh8FuVf5VVBXlU1
            ZoEQ5Q6vceomVxwu8jSA1kGLksrnyqApiOvTdrWaehKQQx54iAjvIKqr8r8I9MS8
            f36VzXv6XzrfSfC5oPDrEBtV10hJS6KAQABqvC8p2tG/kJi36ACfFmCyZLZ6ErEf
            0akHHqwLpf/RIbAnFXxlNn4acY2WBi6suLm5OStJEfrF06rpZaFIKv+hFXk+Uv9Y
            8PXjNbGHXGwI9yG24KSZHyOdiPP96rvz+14y9gkwQjT3tqQZOunOYE/pgib6AP7C
            5YKnsn8PGFPmzHUBnS+ufhrFJsjP8tKBP2AHMfh5yhSCc1WSMYecz1iqI3vHsDuq
            w/EGqWvgU22Prxec1b16eR0uBkIrsPJ1nsbLGfU9fOBpSo5W2TctDGkbkHsdH5qn
            mLtoQChRirdhOh5kjAof9XoZ09+VIagOTfawkb4nqVI3rOVc0jrwYZJ/Ldo6NW7v
            SPyXwemY2cr4lg0xAWJ9Hbvs1353Vg2JJ2Os890ctxRlr612ftUEA1nheQqjq+3s
            Tjd2+xGMS74eY01vUK7tMq6zC13hqbMDe/frBug8ABvrOVsnLStHS9XUXislIs3S
            XAGZAhzPpV8FgrxpdkT/EBBRq0cx2ylT3BzBEZDtOUumioPJfd+BWhYstma4ce5E
            VHDl11RWG+0l2e+Szec0dB833GG0Eyz4JLOHzYAgLqwab+RnQMvtJxd5dHeQ
            =7WfY
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    unencrypted_suffix: _unencrypted
    version: 3.11.0
