---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: authentik
  targetNamespace: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.10.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
  # install:
  #   createNamespace: true
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
