---
apiVersion: v1
kind: Service
metadata:
  name: readeck
  namespace: readeck
spec:
  selector:
    app.kubernetes.io/name: readeck
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
