---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  selector:
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: linkwarden
spec:
  selector:
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: http
      protocol: TCP
