---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: arr
spec:
  selector:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 5055
      targetPort: http
      protocol: TCP
