---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: apps
  path: ./apps/headlamp/overlays/freeloader
  prune: true
  wait: true
  timeout: 10m0s
