apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - services.yaml
  - meilisearch.deployment.yaml
  - chrome.deployment.yaml
  - karakeep.deployment.yaml
