---
apiVersion: v1
kind: Service
metadata:
  name: karakeep
  namespace: karakeep
spec:
  selector:
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: karakeep
spec:
  selector:
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/component: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: karakeep
spec:
  selector:
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/component: chrome
  ports:
    - name: debug
      port: 9222
      targetPort: debug
      protocol: TCP
