---
apiVersion: v1
kind: Service
metadata:
  name: trawl
  namespace: arr
spec:
  selector:
    app.kubernetes.io/name: trawl
    app.kubernetes.io/component: solver
  ports:
    - name: http
      port: 8191
      targetPort: http
      protocol: TCP
