---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      version: "~0.32"
      sourceRef:
        kind: HelmRepository
        name: headlamp
  install:
    createNamespace: true
  driftDetection:
    mode: enabled
  values:
    resources:
      requests:
        cpu: 128m
        memory: 128Mi
    watchPlugins: true
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.4.0
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
        installOptions:
          parallel: true
          maxConcurrent: 2

    replicaCount: 1
