---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      version: "~0.32"
      sourceRef:
        kind: HelmRepository
        name: headlamp
  install:
    createNamespace: true
  driftDetection:
    mode: enabled
  values:
    resources:
      requests:
        cpu: 128m
        memory: 128Mi
    pluginsManager:
      enabled: true
    replicaCount: 1
