apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: open-webui
type: Opaque
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:fm9kzQ2w1lAygS8WNBDsSJn1dlBRfGAo8Xkhiw3bmRErsJO9nGCoATIyqtUnlLOkerV9pqigL3iNf/NND8o3Kw==,iv:GIknyZOGJPkufI7ACGu7sVuEgvT/+N6rDoUN+d/4YxI=,tag:Wd6RgYCRxarAFwkoRQqMkQ==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:QLewSMvd5fq/wqHooOo9XMwDmHSa7h2Lqhqepm/YMfa8H9KzAU4T7Q==,iv:g1gpMRX9/8kDLswd4zGNf9UM7UbB6qlM+tjBQtoLa8o=,tag:Kj74OpzPD+Uv2Ph9dlZUpA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3pzIL3TaG7OA1gvH1AHNExNjmLXhrBqYUNFhpqCKfwg0SNj9iWRygdH8exbWqrknpRku9NsOngAWzd/8b1ZERg==,iv:YPWPJEVJKyNiFXtBpRaRCjtx5/x46sNLTYVlI33Xwi4=,tag:RzrvsZBnFHCMjNqwTcf/Xg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ckl2U0Z4NUViei9QRnlm
        czRYRkFzanlraEJvSUx3WHNpanoxTkhTM0FrCnhMeDJ2ZGhFTkxULzRqUGtURUpN
        RjNPd0dxY3RpYzZEeUpWUkpkRDgrRjgKLS0tIHpjdkFlM2psdTFtTmJ3NFE3RTh1
        OHZSdk1KZUluczhrRi9sVGl1WCs3U2sKZTSskKJ4t0/9KuAXTT9iBs19YC5fGiLT
        7edJ7kcyL28QAGFveXa3YXNOXjGTvYcu7NCV2YaJBfPWQE3wbuetKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdS9XMnB5eFFSeVhmdWtU
        a3VGcS9PSk1BUkJ5c1VJY0JrVUZ4UVJweHhZClJHcEZYTVExc0xRUVJGZGJDYVVZ
        NFVteHlKRUoyMk0ybnpoeWZ5cGJYR00KLS0tIHpPdmdLclNaRGhET2JzU2VXS3N3
        TDNMWExHb0pQWTg3czZZR2JHL1lpaEkKhvqVvwqV6k3K6jJN4mQrZyMjpvANpbzF
        BSF0cc4etNWoqGvz3DCrMU8PjXSZe0LVmKlAqMeH6qqv4IV59o1tGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T23:06:29Z"
  mac: ENC[AES256_GCM,data:xYjHkKSobiZgMPzLhlEMHAIRD70x62T63M1pG29XP/ym6GQ5oDD91A1h+JDbHr+AOdaYcmQyzTD+sqeXtmk/xgdGdpVxWKFTlr4sQgsXBAG9sZ+kvby0YB+gqTF3WqMWkvoZ+fF8X0C5aOCm3G2nDWMiIwZ0El469VhO+seqkFI=,iv:PpIt+F1scOM5/lENoOpfGSADKWphIbKsUveXRQv9M/o=,tag:x3vuwmr7ZlkyiH+u/h+tQQ==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-08-12T23:04:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/8Cc66A9J/wCzvxF5EA1tzzddnkNwgh1tLPrHBmQ2Jn1CY
        Jjwe+BkKoNce3Ks26m5IQeBssPn0Pf/uRZ5WCTqdFxgR6WWOhzkiuW4pqvhXgUW4
        Use+iEf2Tx/aGnIGncmCmZvVXXp4gn6OZsYcVfIxTUS8KtsecMpM18jQgGmeZvw/
        6USYFDLMZi2fl8qouEzsXtBxzdahbkoNJcCbUEgcqImBkPRWlRbLrcC8O7Z4SX+j
        AQsh7C+TxxzRMUoa+hVaRD9YG9FwelsCDqyia9BmHVS02cnMgJVclJrilygqgOqn
        qzUKd/k5Vb9k6qg/9EYivkROEVdpKge5sI8wPlBdH4vFCpfI0yy1OiSfpie1L/UZ
        6QjP7e9P1SBqA6YjPXBcBdAyZwF5uAilap6ic/SHqpcyc4U2xsxHwlDn08lVE6cL
        VM/0QiAW52Cbw98J4xKh6FgIROSbaZtt+VAVTd9/fWYu33Sh6qi7BeW1g3Uo/jCB
        QLSl4p94zMUhfXmyq4zv7/pUJaFE2UbMYdyYVXdr6+hDcrbUy8rM8iLua/Q5u8Wr
        b500mryCNKt0KGBUzEyZls4Nf1SYUoNXG5qiHDu4ETqpEju6rvQ6iJCa6RmEmFb4
        5x+7tAe4qTCHvx0r0eTB/Csp0m41H4/HIeDvPI0q1A+TUC7V+F++PIpRkmgkfpTS
        XgHGjPY+6QcJhBvxmE04zzFSe21zcvWvn8hDpxsyKMVSDdaRCcKwplfFqqW7/upZ
        0qPYORGtheX/9Fbf0LresYXajmoDWREhVFZr8F1/Jd14yKUYyaFLJsIvUzubbdo=
        =VuoU
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
