apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-custom-secret
  namespace: bitwarden
type: Opaque
stringData:
  globalSettings__installation__id: ENC[AES256_GCM,data:kN0ly+jwh8fQ3+RtjrDfAUcGz2tG5kBEAuYAXs/f0sg3w6Sa,iv:E7JmP9weJZFAhsmGvQ+MyWEPC43mqgElQdSxcHoAv5Y=,tag:+1QGMJBS1Wya83NqGhzD4Q==,type:str]
  globalSettings__installation__key: ENC[AES256_GCM,data:IspDidtOi2Hev/LWDqQAYAsexoY=,iv:mcvZevXV4LnQnr4RJpOXEBalwkK9gTjL2KlXEiJu3MU=,tag:QAG41f53F8GoHE98CV7P3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdTRROFFKaDFPM0pFQWZa
        eFpmVEVUMUV3TFVqNG92bkFkLzNZRWRrTURjClBZS05TQ09za1JJN3lYNTBWYnhY
        WkdNZUoyUHE0UG9SWmpPN1RNZHVzNlEKLS0tIEVVUXhmcVAvZjFrUnN1Mk96dm1J
        NUp1Qlo1bXFTQ0w1dDhGSTRkcjJaczgKTf5Wdni71mCxqKoIb4+rr9eycXRKXemf
        s4kVvwBTfMkGL1DdGeQXE7uer0/1OcSqY0PTuagIFhP/Eoei98OkPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dVViYlJLbk1SdVZFSTJn
        RDZ4dDMxUHlQMU1SYXZnaHptTmFFUjNvUkRFCjJnb05sYWxzbTNiVXFVNG9tckZD
        d1ZlTHVTdkljcjRtUy9LTFc0WG0wTW8KLS0tIGlnYVhVTGIxdkYyTWhnQ1hVYVgv
        NTZEVFViVDZEOWF1Q0dKTHcvVjgzKzAKZn7J8R6/vHd1jNnQTflxF0kcxnqaqGCH
        GIfrctorFhJF2hFoaWStuw3s/31ghkyDWebMh9MfFPtncHZtFD/y8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T06:05:22Z"
  mac: ENC[AES256_GCM,data:kh3jvtPzYPMOGfCKNyOt5+PA6vYjRtWoEgGog0itqA3zaDJ5L8+MOP4MIbM+W3+QXNiYocJzqGvj9mEQTtJX5XoEVkCf1JNK6TUh/h4k8DfZAJYWow6n6gOAbirqG6JuoydYy+vvGqI4h25t+YS9XFx5l0I85JgifMSX76tndZA=,iv:YFYqIi7Y1IqTpL/g8W8m1Kdow+/D71xJRtJs1EYAvoU=,tag:hbD/S6qViXzhI5vSTtbLpw==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-05-25T06:56:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ//ZmYh9nwozSrwtzPKYD6LP3N5a4m7d4bHxd5cgtMsIQrY
        1fg346N6CoZvBVX38QGp0l3OrX7ljBMy4M5c63vwr9JUX8PlOQ9ce1sB23GVjcTp
        ygulmFKZ4pVtP+VzomBXwedoIOs4h7svPfRRCUdcpfSb9cm+1JAyGUyPI57gv7gB
        1JCdDBWrSN2zcLityD6mn/uIKuZCwbeHTG0s9XB95bYRk924a9hNNNzZr7RgczpN
        RdtNoAKzoR9N4it3gTmMKk0i1o7o9C7ivgrmseLevppSGcGWKlAsWa76sbjScnFU
        zQAhBu67n/7AM+1aj9fQt6sCkhpfnWOqPk7bQB8fEz7wQJNc7EluqYQ9T4RmiaMy
        pVY4Z8f6OSNZi569jjSplC7ULZB8PYoBYyyh3v+gkx8RHUqTFQmD24IqM24Ck6v7
        ipSYdQ6cXhY+V72Ja8kZ737P0lsPIkOrxoelHlU/8u0UiZ4jU9S2KYVFjWr2W6DE
        Kvz1jdefztnfiSO0ICgBJ4fsCJQwR1VWXxXyWMYSZD+d6k+AUlZ/dbH1eZ+1lAMN
        39L9Kt8pAclSS23efAYg3e/ZBkN0PrGurpwWaTsVswlz9XS73bpLKwNXTBVmQd97
        lHELHfp1S7YDchOYtJVnpXK8cdUldQq1nmR2PAEhFRThT4Hov2OC80X9TlknAyjS
        XgFx9UEzCyEwioqu/+mcSlSzxg2j/SGJaqfkCMhpeNz/5o5pjtkIPWyz0+50dBLH
        /Aay95WCMNcC10Fm75lo/dtyY/ii0nv/9BVDNzMIRQB9dLMuCG0XB7jCaxI6U0U=
        =NwHd
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
