# Backup credentials are provided by ExternalSecret s3-credentials-pgauthentik-sync.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-daily-pgauthentik-backup
  namespace: authentik
spec:
  schedule: "0 0 */4 * * *" # Every four hours
  backupOwnerReference: self
  cluster:
    name: authentik-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: authentik-s3-backup
