apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  storage:
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 125m
    limits:
      memory: 512Mi
      cpu: 512m

  bootstrap:
    initdb:
      database: authentikdb
      owner: authentik

  postgresql:
    parameters:
      max_worker_processes: "4"
      max_parallel_workers: "2"
      max_replication_slots: "8"

  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backups-oke/authentik
      endpointURL: https://froaw0vigiem.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
      s3Credentials:
        accessKeyId:
          name: oci-backup-credentials
          key: aws_access_key_id
        secretAccessKey:
          name: oci-backup-credentials
          key: aws_secret_access_key
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"

  priorityClassName: system-cluster-critical
