apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  storage:
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 125m
    limits:
      memory: 512Mi
      cpu: 512m

  bootstrap:
    initdb:
      database: authentikdb
      owner: authentik

  postgresql:
    parameters:
      max_worker_processes: "4"
      max_parallel_workers: "2"
      max_replication_slots: "8"
      max_slot_wal_keep_size: "5GB"  # Limit WAL retention to prevent disk exhaustion

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      parameters:
        barmanObjectName: authentik-s3-backup

  priorityClassName: system-cluster-critical
