---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-s3-backup
  namespace: authentik
spec:
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  configuration:
    destinationPath: s3://pgauthentik/backups
    endpointURL: https://froaw0vigiem.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
    s3Credentials:
      accessKeyId:
        name: s3-credentials-pgauthentik
        key: aws_access_key_id
      secretAccessKey:
        name: s3-credentials-pgauthentik
        key: aws_secret_access_key
    wal:
      compression: gzip
      maxParallel: 1
    data:
      compression: gzip
      jobs: 1
  retentionPolicy: 1d # Keep backups for 3 days to minimize disk usage
