apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres
  namespace: authentik
type: Opaque
stringData:
  host: ENC[AES256_GCM,data:O5EEMsfaCjZ815uum16G0c77MKnCC4qiN2bW6sfkyJlfJueguT7eGRfInkfM/CDHuEOPvmISgVVqZZg=,iv:aaQeIkWoI84lRJqFnvHWeDehJCwGcIm1Fhm2agGKSuk=,tag:Zl8Dvxb+dlr5Ejw98d/f+g==,type:str]
  port: ENC[AES256_GCM,data:K5ZBQw==,iv:tNd7ZCOH/jMg9qhAl6CWd+DSGfzc0v8MyuCGpPbWUAI=,tag:Y+mP+woutGWlyIcweV7cdQ==,type:str]
  name: ENC[AES256_GCM,data:BvebZg4cWcFf,iv:C+m7FqP4RDPP6E+WTMliV556rRsfEh5QQ9HWquIK3yQ=,tag:Lt4uBFZfvuG4J0HsBGP2qg==,type:str]
  user: ENC[AES256_GCM,data:K7yyp4rg7JhDRNxn,iv:TLmILC7QMe+dFqs6dHJ7/ZT98QRgyLFJSVsYiKZiIL0=,tag:OhBsg8kdfWyBB8w93FI06g==,type:str]
  password: ENC[AES256_GCM,data:OkPzPejVHh6HcjUegmoIQA==,iv:xsFwR1oC4G+BdfImr41wDMiol25fC5sRaVxCaTDpP3c=,tag:/B6vsBjJemeUdUBop0T8qA==,type:str]
  sslmode: ENC[AES256_GCM,data:PJBG8pJ9/g==,iv:rRHBw8l3cJ186ERv9cAOrjIS6D3wLbovEXsharuO3dg=,tag:sH7li7rNWJqucDSy9fS3Rw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcTJudTFkN2VPWVhDU0k3
        Sy92VWtkbnlHZEpTV25yd0ttdncyOFRkK0FrCmZCM1U0SUxkT0RPd0x5RXUxbUtu
        M1V1TnJ5SUZXZlRyLzFmbzFVMTR4NDAKLS0tIExQR21TMlBzNmRyelROMktZbGs2
        T2hacTVCUStqUmZoaXFXNm1MNVVZZkkK1CDYpPYgC8IK9oyshG82Exf8CYuR2UHF
        IkiIy81GR+CDZPl6CS+PNMDihKe9DxulEuRUSfhdYz22gyxGTEL+5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1se6vrwdg3dvwkdg9ysgvsgd30cqxvm007sv4mn0tygjym854g48sllcx9f
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eWc1aUUwanFxV1JMS0Uv
        RmhTUFYwS01DUWJGd081OTBWOWlhd2tZZlc0CmFyOThJNzQ1bkxsMTZGR29xM2R6
        Y3lxWXJtWnRYMHZkVU9ZZlRqVlhZNEkKLS0tIGdmZ04yaGVrRDJDemIwd21UQzdo
        ZnNhNGdjcGVZNFJUVGtMSWNiS3dBcmMK1Xt8P7EeyZW5YHNe2TXHTpG+vRspOXAa
        46zL9yWL+DwTLuL43mI2lefpkAsXmH3Vh4RPJAQ4m5I45LKORZk4hQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T19:38:30Z"
  mac: ENC[AES256_GCM,data:gDgEzmIpCa4V2pAiTl9PG40UmX68egNyEtkyDH/lQfCGpiLM0a5x3s2LyymseGOH6HGCAJiDu6G2qElmxuqox+PbE628mojHoz5bGIzY61MT+FdoyzNWnVaXRuFQXdVQSqbiOBrG7L0w3Z/9WPgq11wbA+Fy+OA4ZMWy8X7fAxY=,iv:cY1YhdTKlBdHzbsTc28HmCConrAsEI+scDNV/X7vG1g=,tag:GMbttgNOt5UPqoE49GNKKQ==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-06-06T19:37:16Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/+N8jSxIRXsi+1zfnRMOTgJrdfgYgTi2ya3el6MDdFTatk
        jD1wdwt1pPwIagQ/5c0CyrSvHl3jqQijfNxYmVbKDELokH1i15onXSCyuhxJKOpu
        lV+AHA4KntRIf59a7s43qtIqhmQ7WlSPyxmkxClgKf2xmg3z4QHrdVQnc9pxRydR
        8mNjsAB1tR66az0/4FUos4fBDPvaNfuiff2po+9cqsQDvSVIHLBAKqagPSAduO++
        jrmEVDt0A14sdUhvJHK25XZyn8V8vEqEmczYzULxinlTWqIPdJGT0rkjN2shkbdn
        bZHqSa8gBRHtSpoYnm+bVlFO6i1+2W8sCXMt6bhg4/EhOh0dnLmpLDlQdo70dm1d
        J4OKMwP6zyOvey2kEd2+8upCGxJu0gqUe5ZOH9MLv3fIO1yIkDfLdN2ZJTHPWPl3
        fm7M515DqR9mWSCZaqvKZx5Da7XS1wdAU9yc7d6+uO/VFNy/U+490IxILOphrzQk
        VnmlsEzwNiRsAFBj7b0kqcICkBsTzyeZntAFgJuA1/OkPlOfN/nnv//TwDo66b9G
        oUmtpUlj8BYTTuaFFkIR5H+BIKsnb1hWnZj2cVkh8zjhahHYB0CXOSZKvtYuAlIG
        a6gEYVXF2DAsz7LgOlPOmGF8NnG225qokM6kq+93cnQa2oMSU7hmxjCpm/73Ty7S
        XAGQNziFGqO4MUNx7jKgfCA97fmJZ4NzJCTrJz922pAyN3dE5K9WhwqUAuBjNk6X
        LNZQ2Ab6gObCXVqwKeYpAEHKr1+AdIoKxjrLYhg9/+edK7Jjl/R3Jq4K32j7
        =L/yv
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
