---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secret-key-generator
  namespace: authentik
spec:
  length: 50
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: "0"
  target:
    name: authentik-secret-key
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-secret-key-generator
