---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-rawfile
  resources:
    requests:
      storage: 2Gi
