---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: arr-media
