---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arr
spec:
  selector:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 7878
      targetPort: http
      protocol: TCP
