apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc-data.yaml
  - pvc-mariadb.yaml
  - pv-library.yaml
  - pvc-library.yaml
  - secrets.externalsecret.yaml
  - httproute.yaml
