---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-library
  namespace: grimmory
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: grimmory-library
