---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-mariadb
  namespace: grimmory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-rawfile
  resources:
    requests:
      storage: 2Gi
