---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grimmory-mariadb-root-generator
  namespace: grimmory
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grimmory-mariadb-root
  namespace: grimmory
spec:
  refreshInterval: "0"
  target:
    name: grimmory-mariadb-root
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grimmory-mariadb-root-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grimmory-db-generator
  namespace: grimmory
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grimmory-db
  namespace: grimmory
spec:
  refreshInterval: "0"
  target:
    name: grimmory-db
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grimmory-db-generator
