# Backup credentials are provided by ExternalSecret s3-credentials-pgzitadel-sync.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-daily-pgzitadel-backup
  namespace: zitadel
spec:
  schedule: "0 0 */4 * * *" # Every four hours
  backupOwnerReference: self
  cluster:
    name: zitadel-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: zitadel-s3-backup
