---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: zitadel-masterkey-generator
  namespace: zitadel
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
spec:
  refreshInterval: "0"
  target:
    name: zitadel-masterkey
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: zitadel-masterkey-generator
      rewrite:
        - regexp:
            source: "password"
            target: "masterkey"
