apiVersion: v1
kind: Secret
metadata:
  name: ghostfolio-secrets
  namespace: ghostfolio
type: Opaque
stringData:
  ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:Pqi+mDqmY2ukNeDlZ1UJ8cFxaUMCgNtbd12n/gxb2LLCYdZ5fKUNM8zmosMAV0LqbP8rH/ZFMGEq8lzosq8uCw==,iv:TnteN2j4vsD1anPK0IMPthl5Bp7dQ+6nlqq3Q4U1Stk=,tag:KGwJUbvpoogS4Xk4rBqL6A==,type:str]
  JWT_SECRET_KEY: ENC[AES256_GCM,data:V69o3VzfsMU1sDQAg4bM0znI3KRUxoAAoctpFoBjbCAav8UArM1EK7P+R6utW5XPevQdbHJHu9k5cGFUPGsnZQ==,iv:1sNCE5FW6mo5WpB8W7dsxFePPXThEKxd64JAaRb4L9k=,tag:Id3oixODvI18TwWlrmpwvQ==,type:str]
sops:
  age:
    - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWk05Ri9lM0VFK1VUVFU5
        U1ZGK2pZVzVtYmUwTklqTDh1dkQwS2Jtc0VBCndjTDJORWhDaUp3ajJ6MXZ1Y1No
        dkFXNWNybnRTZDVpWHlJQjhsNUNZSFUKLS0tIFRSczFQZngwbzZyNWMyT3hxdXY3
        K0VmdXF5UzNuekVVZUFYS09WU3IvWG8Kt+ygXiom10iSCInxZtE3cFtqTcxb18Hd
        JivpBpg3BE9GeEIxjWLBRLaatdFg4OngopTiCv4blNUQvjyikfes6A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTFVudE8yRStGUUNzSnZG
        WllBbkt1Q0F4MFZxbE02WjZXdHZDNC8wTFNRCkkxTTFDQldJenNxS0c0azFSdW9j
        SXMxUkRCOElaNVdJNDJBNW8rWVNUZWsKLS0tIGdJQ0lLVGFLeHQ4SVZ6VXpkSk9K
        bGtpeEZYaVk1bHJiVTdlWGJaUGFPWUEKhPkgAbXYjyGs5nswsfBVz7xnSBh+66FR
        OQdsYiwkCW+8FR4LDLM6MpzDxERCCOe0wtYeQt1xfH7K0vbyiHYXlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-26T20:05:06Z"
  mac: ENC[AES256_GCM,data:BJn2aLU7M4Oi220ccEhQ6NcyiwSh/ETdigOc+YJKvkibJZAFnCsM4AgkXB2TvHRiuHzQfMGk2j2FzrVEJV4DUJWkZipOIuXoxlHoITdc7Au0gRXAQCTOAXD2XDIPQpUsj0pdvTZu/LOzTXb059ylRcLRkcHdMhkw1Gv5oSqmpkw=,iv:6WlB1mTEu3fB1ngDLvU03Egd0WQaqH1WQYr8eY8aUfg=,tag:oi8Tb9PieSpeHmsqy1juWA==,type:str]
  pgp:
    - created_at: "2026-05-26T20:05:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/9FVdfc/TWIBUIpXxneE48xrBcWxpCzd+4suVwxvaZhXJJ
        SGb6IrW9dvPsFWIDQR8kA75QBRhq3jBaxy2ANJsgNLa496pcF/X9bq0F8XhKDgmz
        gSX3W09PAHNcBLWKlshygP8JYC+R04AgD/H6GJoP1XOM0/X0noS6aRa6fN0prCmT
        OdKMnM2fFX/Bj/BkHUY1awxOEGlnN1wjQHdmBBzcsc7sqxoo5/4Qjn8T7nOBPFZ4
        i4uTDaN+5e4HJ6LPlfuKkyi+fEDo+SS5lP0ufboDTquOnBpbX/4CHcxBc8ZUQ3Kd
        WkgBLn+dQjg81KmVJ2apwcdh/rqY2l8qvXMcS4b35bfUU1t4qyWogGFzcBvSAnZr
        nO5QK3IpgB18Xt8vLunYC/LC6MNOhf33Xb8vQl0Ki6tW1y2K7EoRa9qVMXfHmdMh
        MMCCm2qk+2rfTS8EsCqx2MWTlM2TH/75ygOykve357pKRJekLaGbSLeD8M9YHmZ6
        TcD73st93EAfKWngRQFNKPveM8BNxttrcuT8taLoWUz2Pg0qx6cfIq5QhRB38ecI
        tpVw0kAApu+RSduEzx9eLDtRUs8eCmtk7HFo4IGnr34rAC0oNm/o/LUMDKN/ZvFi
        H47gsNZTUBpzMZ7zMxbalUwg3rFRfD72B6SZZHFzCxZAqdIU7shCKIKpA+jRqBDS
        XgH6fk2+oK3QwtgM7km6VopaiJFXSsLYy88IphUpHp7yqRw9FFMD7jArAVidsSGB
        aOBOmoWNMxy29HDM5/tF3EEBBk0BQCR1yLnwweBWBmXOGkXwYBjnhexTzaKUq0M=
        =Mft+
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
