apiVersion: v1
kind: Secret
metadata:
  name: reactive-resume-secrets
  namespace: reactive-resume
type: Opaque
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:5nxrc5wvBV4S7gT9XcaJq4DLs6BeY2oKx2ZmFwD+CUnkRvvjvqaKP67LrD80vDo07KoERv70NlFtoe3BKTL0Sw==,iv:Gnyp2yuUHMrPe1w58qgFkBG82t1KvIkqd2bvedq+gw0=,tag:u2lCcqwWJLrUAhcI2k+X6g==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:S39sGjCeBFVMoATuo2Yq1Na6lcr5JYv4z781KFS9WzcvWqJPjgcmfw==,iv:w2B+7DA2rs4u96i15DhGIT/TYhRlNaIernhfRwpiaag=,tag:/VtTfvEhi5xOYXcOrTGMaw==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZqxgebzO/0fFLYicYkMuKXmzM6CXctFbU6o2UXAktE8G4pUKy4hWjqRofE5mJezU36QEzrc8FoE60r+yP8E0KQ==,iv:LWLqUL5DGO0/G/fcj29ERTstfNdET2IDrAxgOxDDyQk=,tag:OSjHerRNopc+I5eOdDqLPg==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:nqyt17TZZzvf7CwYFKzNCpKVKmkinmSAHpkpg600K5SXfm5cCsC8s0wLimxF7oZEWd9WYd6PRlCZyilPztVFvKgQVY+aqXMeMeb72a3ZJ/azmbDqG+MmqUvIAmM7ZNJuD1lbsP1FXAXU8FSF//YwojeAgtLLBpxWm2X/cV925SHC5fB7sJ/YshA7sul8Zpc5Ty2BkanrU7NVauN6e/3wrY1LQA==,iv:pJE2wsE9uAw5s0iKs8GJmUg96yd/l1hN6erf6yCsGs0=,tag:psPkE1rvArBnPZUi/TEJKQ==,type:str]
  SMTP_PASS: ENC[AES256_GCM,data:4XW58u6SQLUVoQTGtFDnJaotUsk=,iv:XVg7h2XxzfFju9JnkGGIJFym+XIB/EqbYKCxo4ljumM=,tag:FwRUDEb3zGMWtbuGHzkCEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RWtqS2l3RThIUFJFZmJC
        WGFwTFY5MlJ0dVNDUjJBdVJXcEltMjBoSUNFCnY3eDFCQnZ6OUlXaHh0bFpMZy9K
        TU5ORHFGc1FzWFNjc2NDeFN2Vy9qVzAKLS0tIDRzQTRlbnB0ZmU4WHRxS01sRjB0
        aGVMVnVCWUFSUC9tNzgwbmV6SjhtUFEKeMx+aonBVj5xDyG1Agi2cQiY+t30xTQh
        CuIXqiZ4fy9G/U/ODObJihs/EA4mIKl3E2VqC4a2ARCD3G/o4CZK8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aE5HQ29nRDNIWUY4OVBQ
        WFVnRVZCZ0xnVHUvQ3c5T1RNQ2J4OHU2NURrCmtXYXI1eGEwNXVhdzIyVHV3aGk2
        NVMvV21QTGFrT1BrMkJoeXF5UC9JaEEKLS0tIElzalAxK1hUS3U4aXRlMEErSWpD
        UXRZRjZ3dElrZ0JkSFU0ME96OWs1M2cKVqWXcQPTUFkUoiFW++OBoZd1vsU+1nrZ
        VfdAmnKcrbqiHiIyYfYT/8zpWS3BrXmgB2JhKIMiZjHRwU8AGgB6Cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T06:46:36Z"
  mac: ENC[AES256_GCM,data:5AQ547MzlIxkSBXjleNwrAYdHyV4DydHNeNZlHVMWvtnJQQJJ58+y/Ea/zZrbkgJCYognGdRWokQb63GuksUKJEaZAnRFc1GO2T7fXeoZlTssszUG2ulvttwuw3Qi3ujHWRuuB7JexR0KUB+CiypP4I5YnyPIdp8tT7KpTB6cuA=,iv:1FspZMl66/WLYantHnS5II69mLPMHxzfGe1twXRRNss=,tag:sjGa8rGA2g4yZgGDxEk5uw==,type:str]
  mac_only_encrypted: true
  pgp:
    - created_at: "2026-08-10T06:46:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaARAAia3c002IhK8vcGSSpVWZHCBTKQtI9fWxL7kuOwIpLXI8
        UV1CT9ZvmRDKv1nTBfQKIa3pVFWrjNiDXxCn5JXnS9vz1JoVsRVtmLRQkVWDNf3S
        ljIrOb02QRI/3lev2VG28sHU3zdZqo6fNuqKJ+FSVx3F093O40+rDpVBmZqFICEF
        1JUdLu7fc8C/C3BsudkhCN1gluP5wJIcxH166TApD8HPsADlqAd62s9PxmnfO3Fz
        UPDykGZ1pCvSF+TFeZffgUXuxeZ++SQuyTq6Fu+81b8ENQ4jEitWr+WaoTcjByvr
        PH3nkPt8/B26d9sJZ4QrNkG3yYPP2ZRlpBQn7JeOEM26qEqh+n/LuXWHrDzdTs0u
        yELiooiJt/Z69z2yE6xRArHyy1VmIhu16z3X2YdZBwfub5vXICY0altoZDw55a5B
        cY3D4sU9Pz1XVeYDXjDquBYXuB0DwS1tLVq+8erGTnGvQTNkVtF09tiQk8sgiDN2
        sKtRQyjFcpWmNVCzUGyW9MqmGxR/VgiwsE0yF1/NF8px6T9UNZiTKaNtAaxH04GH
        73gDPlpRSqW3ZthK4zoh+nwLj1x4hhV5RPqkyKnvBKaTql0Mej94kSXsQ7oUBYw3
        nXUEVIoWf7MKgR63yL+aGoZVzdrKS3SkMjdUcQ71cudwYLdT485dc334CjC8+gHS
        XgFl1zTTRoqyN+wYf9wVmHCvRaT1PApa9wUAWWzDfZlT5FMURE+yWm1PAE0IxLJE
        ITySDB+XVnidYp+7xjE4BNcugHapB88VVtJJY0+O+oFIS3fGoOCKyeNN2/RNEeA=
        =pgSV
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  version: 3.13.1
