---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-library
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - nconnect=4
    - rsize=1048576
    - wsize=1048576
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: calibre-web-library
    volumeAttributes:
      server: nas.homelab.blacksd.tech
      share: /volume1/Apps/calibre-library
