apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobookshelf.yaml
  - grimmory.yaml
  - homepage.yaml
  - karakeep.yaml
  - minecraft-bedrock.yaml
  - paperless-ngx.yaml
  - readeck.yaml
  - vaultwarden.yaml
