---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mindwtr
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: apps
  path: ./apps/mindwtr/overlays/understairs
  prune: true
  wait: true
  timeout: 10m0s
  decryption:
    provider: sops
