---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: karakeep-nextauth-secret-generator
  namespace: karakeep
spec:
  length: 48
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep-nextauth-secret
  namespace: karakeep
spec:
  refreshInterval: "0"
  target:
    name: karakeep-nextauth-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: karakeep-nextauth-secret-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: karakeep-meili-master-key-generator
  namespace: karakeep
spec:
  length: 32
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep-meili-master-key
  namespace: karakeep
spec:
  refreshInterval: "0"
  target:
    name: karakeep-meili-master-key
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: karakeep-meili-master-key-generator
