---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arr
spec:
  selector:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8989
      targetPort: http
      protocol: TCP
