apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sonarr/deployment.yaml
  - sonarr/service.yaml
  - radarr/deployment.yaml
  - radarr/service.yaml
  - prowlarr/deployment.yaml
  - prowlarr/service.yaml
  - bazarr/deployment.yaml
  - bazarr/service.yaml
  - byparr/deployment.yaml
  - byparr/service.yaml
