---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-bedrock
spec:
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-bedrock-values
      valuesKey: values.yaml
    - kind: Secret
      name: minecraft-bedrock-ops
      valuesKey: values.yaml
