apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ops.secret.sops.yaml
  - ../../base
patches:
  - path: helmrelease.patch.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
