apiVersion: v1
kind: Secret
metadata:
  name: minecraft-bedrock-ops
  namespace: flux-system
stringData:
  values.yaml: ENC[AES256_GCM,data:A/UlGoxdFw9nDKyVk89E91OGCoONHWFRdPeyl0fmQ728Wt6XFOtWnjg=,iv:reI2YzQLGV1t+PqmwJNsAQOcOw6R4wMGcyjkQu9a8pk=,tag:ccLz2490lVffpIAxyTB7/w==,type:str]
sops:
  age:
    - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T0tjVDVPQmV6NHlZWldV
        dVBxWURXYU8zbFc3RXA1QjNGVFR2RmVCWmswCjZLU1dmY2Y5TFFVTU94YmdKZml2
        TmNLcUhUMy9qMU5jVzNpOXBETlVWa3MKLS0tIFFyZVlkNGN2cE1NM2dGSi9hbktS
        T0Q5ZHN5cUFnVTdjbWpLV0FDc2tEeXMKY7IUxFJATPfglKbThRgYSa32hDN/n75G
        Z05Rzt4TFsbZMDhaAIQut1HnDC9uiW+cVOJae9Kzv/NJTtKnXhoVkg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2xQQTJWU3pYK3owd0xu
        R25UelZQOGVISmt5czNtV2NTZENtM29lRjN3CmhOVTdPMFgyU0xTMThUendTU0U0
        ZTczMTg4cXREYzdWN0k4UXRtR1QrcU0KLS0tIDFLTDFXZkFDYWs4dkZvS05XcDMy
        NlpjMGdlR2kyNEhuZlA4NkY0cE94bzgKp1D3b85WD0YHQcvOrKDvhRQhxFz1f3af
        rOC0ZDoGt/COoXzFTIv4+XCz09v01b4RMj+B2flAmbQJ9LMpDX17ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T07:48:04Z"
  mac: ENC[AES256_GCM,data:Yfewx/w/pPk2z7NA2aRJaqqXGrFQLSIJB0skp44Mo/iQnT5WwqxiuqDITMr3GNZS3j/nBNlummTh3A7nEud5qvdtt0h24RpH4sLmESSnHsJ8sWFMNJ7S3Dv78anVaq1nnW49JOiGAjdlp0Axht7ATZ/mnSziQnKEVKyL6YbfR1E=,iv:iq3D8bZvt4sJqHcXMOnVHEkgIy8BeH4V5jiV6i+7sD4=,tag:IF4sOkJu/dGtNEefEcuTXQ==,type:str]
  pgp:
    - created_at: "2026-03-24T07:48:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2fheYx7el0jAQ//e+ogqXDwWhK0/nwtOfAZnIsqzTPdO4dmY5Kmc72wAw4g
        go9BzVVsTK6EQarH94ymfeBXlH9oyU2N+F5Kko267STNgt91NFR6ckkwjEq1Tc44
        e2EkpM8NO5/LwihYsNluoSKWyH1E+fXiasxpXa4Rb9X5tp4MW3XLWiZa9AYXYgiD
        EtjBSRJbmnOV7n5QbsTHT2Md3GXntQUe4EeJzxw01+viIVn2RKw3FyYby2viOEhc
        vtr5GiUYkTCt7osy5+npAs4uDh4eq3jdKMbyLWclTlpSub/SMFI9UMt0l78KNshr
        lkfqa2VQDfj4vjHmM7+8sWUeP86K4SuYo0WFdipr3tKtTNpV67aeKcppDx+5vIRN
        ttSCf5ZSZdswjKAcmEfcH1e3rDN2jythdDtJtt5MQEV6cNN0ucq9yWoyqW4csP8f
        jQE6ZnS91PWGfxSrLOsiwayVcGRH2bZC6GN43bzDMwXxd990N9z9YUVPE2VNTlU/
        iJwSwbZ0gs9BeLjJOB6PTZ3EhVKfrbiRFfBcOZuba2wHr7XyCZeiq0mTbebLLwiz
        NhMcRDIiZ3KjUZSc1iQ/03vP4CXgKwatNIuUAA4a/0TlwDnNjTOs+EBK+WkinL6T
        mP254cymc6f3o/5lXvxd1UuZn6JGxhg016egLoC1HIU260AxBMGjS8TiOWCCq37S
        XgHU7mA9TeNemH+Qe0jzzyaarV3T++8edTSqWyhA5eqXOGRHIJSthj9dkLnJ8bMD
        LCnrjpr3dDrz76yfk1v/6iam/0NiDQw35j4yIuruPU4MdWFYov7rmI7bzqD+VkQ=
        =+QTl
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
