---
apiVersion: v1
kind: Service
metadata:
  name: grimmory
  namespace: grimmory
spec:
  selector:
    app.kubernetes.io/name: grimmory
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 6060
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: grimmory
spec:
  selector:
    app.kubernetes.io/name: grimmory
    app.kubernetes.io/component: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
