---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/component: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/component: web
    spec:
      securityContext:
        runAsUser: 1027
        runAsGroup: 100
        fsGroup: 100
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.28.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: PUID
              value: "1027"
            - name: PGID
              value: "100"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
