---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arr
spec:
  selector:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 9696
      targetPort: http
      protocol: TCP
